/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.reservations;

import java.util.Collection;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.microsoft.rest.ExpandableStringEnum;

/**
 * Defines values for InstanceFlexibility.
 */
public final class InstanceFlexibility extends ExpandableStringEnum<InstanceFlexibility> {
    /** Static value On for InstanceFlexibility. */
    public static final InstanceFlexibility ON = fromString("On");

    /** Static value Off for InstanceFlexibility. */
    public static final InstanceFlexibility OFF = fromString("Off");

    /** Static value NotSupported for InstanceFlexibility. */
    public static final InstanceFlexibility NOT_SUPPORTED = fromString("NotSupported");

    /**
     * Creates or finds a InstanceFlexibility from its string representation.
     * @param name a name to look for
     * @return the corresponding InstanceFlexibility
     */
    @JsonCreator
    public static InstanceFlexibility fromString(String name) {
        return fromString(name, InstanceFlexibility.class);
    }

    /**
     * @return known InstanceFlexibility values
     */
    public static Collection<InstanceFlexibility> values() {
        return values(InstanceFlexibility.class);
    }
}
