/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.reservations;

import java.util.List;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ReservationProperties model.
 */
public class ReservationProperties {
    /**
     * Possible values include: 'VirtualMachines', 'SqlDatabases', 'SuseLinux'.
     */
    @JsonProperty(value = "reservedResourceType")
    private String reservedResourceType;

    /**
     * Possible values include: 'On', 'Off', 'NotSupported'.
     */
    @JsonProperty(value = "instanceFlexibility")
    private String instanceFlexibility;

    /**
     * Friendly name for user to easily identify the reservation.
     */
    @JsonProperty(value = "displayName")
    private String displayName;

    /**
     * The appliedScopes property.
     */
    @JsonProperty(value = "appliedScopes")
    private List<String> appliedScopes;

    /**
     * Possible values include: 'Single', 'Shared'.
     */
    @JsonProperty(value = "appliedScopeType")
    private String appliedScopeType;

    /**
     * Quantity of the SKUs that are part of the Reservation.
     */
    @JsonProperty(value = "quantity")
    private Integer quantity;

    /**
     * Possible values include: 'Creating', 'PendingResourceHold',
     * 'ConfirmedResourceHold', 'PendingBilling', 'ConfirmedBilling',
     * 'Created', 'Succeeded', 'Cancelled', 'Expired', 'BillingFailed',
     * 'Failed', 'Split', 'Merged'.
     */
    @JsonProperty(value = "provisioningState")
    private String provisioningState;

    /**
     * DateTime of the Reservation starting when this version is effective
     * from.
     */
    @JsonProperty(value = "effectiveDateTime")
    private DateTime effectiveDateTime;

    /**
     * DateTime of the last time the Reservation was updated.
     */
    @JsonProperty(value = "lastUpdatedDateTime", access = JsonProperty.Access.WRITE_ONLY)
    private DateTime lastUpdatedDateTime;

    /**
     * This is the date when the Reservation will expire.
     */
    @JsonProperty(value = "expiryDate")
    private LocalDate expiryDate;

    /**
     * Description of the SKU in english.
     */
    @JsonProperty(value = "skuDescription")
    private String skuDescription;

    /**
     * The extendedStatusInfo property.
     */
    @JsonProperty(value = "extendedStatusInfo")
    private ExtendedStatusInfo extendedStatusInfo;

    /**
     * The splitProperties property.
     */
    @JsonProperty(value = "splitProperties")
    private ReservationSplitProperties splitProperties;

    /**
     * The mergeProperties property.
     */
    @JsonProperty(value = "mergeProperties")
    private ReservationMergeProperties mergeProperties;

    /**
     * Get possible values include: 'VirtualMachines', 'SqlDatabases', 'SuseLinux'.
     *
     * @return the reservedResourceType value
     */
    public String reservedResourceType() {
        return this.reservedResourceType;
    }

    /**
     * Set possible values include: 'VirtualMachines', 'SqlDatabases', 'SuseLinux'.
     *
     * @param reservedResourceType the reservedResourceType value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withReservedResourceType(String reservedResourceType) {
        this.reservedResourceType = reservedResourceType;
        return this;
    }

    /**
     * Get possible values include: 'On', 'Off', 'NotSupported'.
     *
     * @return the instanceFlexibility value
     */
    public String instanceFlexibility() {
        return this.instanceFlexibility;
    }

    /**
     * Set possible values include: 'On', 'Off', 'NotSupported'.
     *
     * @param instanceFlexibility the instanceFlexibility value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withInstanceFlexibility(String instanceFlexibility) {
        this.instanceFlexibility = instanceFlexibility;
        return this;
    }

    /**
     * Get friendly name for user to easily identify the reservation.
     *
     * @return the displayName value
     */
    public String displayName() {
        return this.displayName;
    }

    /**
     * Set friendly name for user to easily identify the reservation.
     *
     * @param displayName the displayName value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withDisplayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    /**
     * Get the appliedScopes value.
     *
     * @return the appliedScopes value
     */
    public List<String> appliedScopes() {
        return this.appliedScopes;
    }

    /**
     * Set the appliedScopes value.
     *
     * @param appliedScopes the appliedScopes value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withAppliedScopes(List<String> appliedScopes) {
        this.appliedScopes = appliedScopes;
        return this;
    }

    /**
     * Get possible values include: 'Single', 'Shared'.
     *
     * @return the appliedScopeType value
     */
    public String appliedScopeType() {
        return this.appliedScopeType;
    }

    /**
     * Set possible values include: 'Single', 'Shared'.
     *
     * @param appliedScopeType the appliedScopeType value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withAppliedScopeType(String appliedScopeType) {
        this.appliedScopeType = appliedScopeType;
        return this;
    }

    /**
     * Get quantity of the SKUs that are part of the Reservation.
     *
     * @return the quantity value
     */
    public Integer quantity() {
        return this.quantity;
    }

    /**
     * Set quantity of the SKUs that are part of the Reservation.
     *
     * @param quantity the quantity value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withQuantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    /**
     * Get possible values include: 'Creating', 'PendingResourceHold', 'ConfirmedResourceHold', 'PendingBilling', 'ConfirmedBilling', 'Created', 'Succeeded', 'Cancelled', 'Expired', 'BillingFailed', 'Failed', 'Split', 'Merged'.
     *
     * @return the provisioningState value
     */
    public String provisioningState() {
        return this.provisioningState;
    }

    /**
     * Set possible values include: 'Creating', 'PendingResourceHold', 'ConfirmedResourceHold', 'PendingBilling', 'ConfirmedBilling', 'Created', 'Succeeded', 'Cancelled', 'Expired', 'BillingFailed', 'Failed', 'Split', 'Merged'.
     *
     * @param provisioningState the provisioningState value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withProvisioningState(String provisioningState) {
        this.provisioningState = provisioningState;
        return this;
    }

    /**
     * Get dateTime of the Reservation starting when this version is effective from.
     *
     * @return the effectiveDateTime value
     */
    public DateTime effectiveDateTime() {
        return this.effectiveDateTime;
    }

    /**
     * Set dateTime of the Reservation starting when this version is effective from.
     *
     * @param effectiveDateTime the effectiveDateTime value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withEffectiveDateTime(DateTime effectiveDateTime) {
        this.effectiveDateTime = effectiveDateTime;
        return this;
    }

    /**
     * Get dateTime of the last time the Reservation was updated.
     *
     * @return the lastUpdatedDateTime value
     */
    public DateTime lastUpdatedDateTime() {
        return this.lastUpdatedDateTime;
    }

    /**
     * Get this is the date when the Reservation will expire.
     *
     * @return the expiryDate value
     */
    public LocalDate expiryDate() {
        return this.expiryDate;
    }

    /**
     * Set this is the date when the Reservation will expire.
     *
     * @param expiryDate the expiryDate value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withExpiryDate(LocalDate expiryDate) {
        this.expiryDate = expiryDate;
        return this;
    }

    /**
     * Get description of the SKU in english.
     *
     * @return the skuDescription value
     */
    public String skuDescription() {
        return this.skuDescription;
    }

    /**
     * Set description of the SKU in english.
     *
     * @param skuDescription the skuDescription value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withSkuDescription(String skuDescription) {
        this.skuDescription = skuDescription;
        return this;
    }

    /**
     * Get the extendedStatusInfo value.
     *
     * @return the extendedStatusInfo value
     */
    public ExtendedStatusInfo extendedStatusInfo() {
        return this.extendedStatusInfo;
    }

    /**
     * Set the extendedStatusInfo value.
     *
     * @param extendedStatusInfo the extendedStatusInfo value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withExtendedStatusInfo(ExtendedStatusInfo extendedStatusInfo) {
        this.extendedStatusInfo = extendedStatusInfo;
        return this;
    }

    /**
     * Get the splitProperties value.
     *
     * @return the splitProperties value
     */
    public ReservationSplitProperties splitProperties() {
        return this.splitProperties;
    }

    /**
     * Set the splitProperties value.
     *
     * @param splitProperties the splitProperties value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withSplitProperties(ReservationSplitProperties splitProperties) {
        this.splitProperties = splitProperties;
        return this;
    }

    /**
     * Get the mergeProperties value.
     *
     * @return the mergeProperties value
     */
    public ReservationMergeProperties mergeProperties() {
        return this.mergeProperties;
    }

    /**
     * Set the mergeProperties value.
     *
     * @param mergeProperties the mergeProperties value to set
     * @return the ReservationProperties object itself.
     */
    public ReservationProperties withMergeProperties(ReservationMergeProperties mergeProperties) {
        this.mergeProperties = mergeProperties;
        return this;
    }

}
