/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.servicefabric;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents the health state of a deployed application, which contains the
 * entity identifier and the aggregated health state.
 */
public class DeployedApplicationHealthState extends EntityHealthState {
    /**
     * Name of the node on which the service package is deployed.
     */
    @JsonProperty(value = "NodeName")
    private String nodeName;

    /**
     * The name of the application, including the 'fabric:' URI scheme.
     */
    @JsonProperty(value = "ApplicationName")
    private String applicationName;

    /**
     * Get the nodeName value.
     *
     * @return the nodeName value
     */
    public String nodeName() {
        return this.nodeName;
    }

    /**
     * Set the nodeName value.
     *
     * @param nodeName the nodeName value to set
     * @return the DeployedApplicationHealthState object itself.
     */
    public DeployedApplicationHealthState withNodeName(String nodeName) {
        this.nodeName = nodeName;
        return this;
    }

    /**
     * Get the applicationName value.
     *
     * @return the applicationName value
     */
    public String applicationName() {
        return this.applicationName;
    }

    /**
     * Set the applicationName value.
     *
     * @param applicationName the applicationName value to set
     * @return the DeployedApplicationHealthState object itself.
     */
    public DeployedApplicationHealthState withApplicationName(String applicationName) {
        this.applicationName = applicationName;
        return this;
    }

}
