/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.servicefabric;

import org.joda.time.DateTime;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * Provides statistics about the Service Fabric Replicator, when it is
 * functioning in a ActiveSecondary role.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "Kind")
@JsonTypeName("SecondaryReplicatorStatus")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "ActiveSecondary", value = SecondaryActiveReplicatorStatus.class),
    @JsonSubTypes.Type(name = "IdleSecondary", value = SecondaryIdleReplicatorStatus.class)
})
public class SecondaryReplicatorStatus extends ReplicatorStatus {
    /**
     * Details about the replication queue on the secondary replicator.
     */
    @JsonProperty(value = "ReplicationQueueStatus")
    private ReplicatorQueueStatus replicationQueueStatus;

    /**
     * The last time-stamp (UTC) at which a replication operation was received
     * from the primary.
     * UTC 0 represents an invalid value, indicating that a replication
     * operation message was never received.
     */
    @JsonProperty(value = "LastReplicationOperationReceivedTimeUtc")
    private DateTime lastReplicationOperationReceivedTimeUtc;

    /**
     * Value that indicates whether the replica is currently being built.
     */
    @JsonProperty(value = "IsInBuild")
    private Boolean isInBuild;

    /**
     * Details about the copy queue on the secondary replicator.
     */
    @JsonProperty(value = "CopyQueueStatus")
    private ReplicatorQueueStatus copyQueueStatus;

    /**
     * The last time-stamp (UTC) at which a copy operation was received from
     * the primary.
     * UTC 0 represents an invalid value, indicating that a copy operation
     * message was never received.
     */
    @JsonProperty(value = "LastCopyOperationReceivedTimeUtc")
    private DateTime lastCopyOperationReceivedTimeUtc;

    /**
     * The last time-stamp (UTC) at which an acknowledgment was sent to the
     * primary replicator.
     * UTC 0 represents an invalid value, indicating that an acknowledgment
     * message was never sent.
     */
    @JsonProperty(value = "LastAcknowledgementSentTimeUtc")
    private DateTime lastAcknowledgementSentTimeUtc;

    /**
     * Get the replicationQueueStatus value.
     *
     * @return the replicationQueueStatus value
     */
    public ReplicatorQueueStatus replicationQueueStatus() {
        return this.replicationQueueStatus;
    }

    /**
     * Set the replicationQueueStatus value.
     *
     * @param replicationQueueStatus the replicationQueueStatus value to set
     * @return the SecondaryReplicatorStatus object itself.
     */
    public SecondaryReplicatorStatus withReplicationQueueStatus(ReplicatorQueueStatus replicationQueueStatus) {
        this.replicationQueueStatus = replicationQueueStatus;
        return this;
    }

    /**
     * Get the lastReplicationOperationReceivedTimeUtc value.
     *
     * @return the lastReplicationOperationReceivedTimeUtc value
     */
    public DateTime lastReplicationOperationReceivedTimeUtc() {
        return this.lastReplicationOperationReceivedTimeUtc;
    }

    /**
     * Set the lastReplicationOperationReceivedTimeUtc value.
     *
     * @param lastReplicationOperationReceivedTimeUtc the lastReplicationOperationReceivedTimeUtc value to set
     * @return the SecondaryReplicatorStatus object itself.
     */
    public SecondaryReplicatorStatus withLastReplicationOperationReceivedTimeUtc(DateTime lastReplicationOperationReceivedTimeUtc) {
        this.lastReplicationOperationReceivedTimeUtc = lastReplicationOperationReceivedTimeUtc;
        return this;
    }

    /**
     * Get the isInBuild value.
     *
     * @return the isInBuild value
     */
    public Boolean isInBuild() {
        return this.isInBuild;
    }

    /**
     * Set the isInBuild value.
     *
     * @param isInBuild the isInBuild value to set
     * @return the SecondaryReplicatorStatus object itself.
     */
    public SecondaryReplicatorStatus withIsInBuild(Boolean isInBuild) {
        this.isInBuild = isInBuild;
        return this;
    }

    /**
     * Get the copyQueueStatus value.
     *
     * @return the copyQueueStatus value
     */
    public ReplicatorQueueStatus copyQueueStatus() {
        return this.copyQueueStatus;
    }

    /**
     * Set the copyQueueStatus value.
     *
     * @param copyQueueStatus the copyQueueStatus value to set
     * @return the SecondaryReplicatorStatus object itself.
     */
    public SecondaryReplicatorStatus withCopyQueueStatus(ReplicatorQueueStatus copyQueueStatus) {
        this.copyQueueStatus = copyQueueStatus;
        return this;
    }

    /**
     * Get the lastCopyOperationReceivedTimeUtc value.
     *
     * @return the lastCopyOperationReceivedTimeUtc value
     */
    public DateTime lastCopyOperationReceivedTimeUtc() {
        return this.lastCopyOperationReceivedTimeUtc;
    }

    /**
     * Set the lastCopyOperationReceivedTimeUtc value.
     *
     * @param lastCopyOperationReceivedTimeUtc the lastCopyOperationReceivedTimeUtc value to set
     * @return the SecondaryReplicatorStatus object itself.
     */
    public SecondaryReplicatorStatus withLastCopyOperationReceivedTimeUtc(DateTime lastCopyOperationReceivedTimeUtc) {
        this.lastCopyOperationReceivedTimeUtc = lastCopyOperationReceivedTimeUtc;
        return this;
    }

    /**
     * Get the lastAcknowledgementSentTimeUtc value.
     *
     * @return the lastAcknowledgementSentTimeUtc value
     */
    public DateTime lastAcknowledgementSentTimeUtc() {
        return this.lastAcknowledgementSentTimeUtc;
    }

    /**
     * Set the lastAcknowledgementSentTimeUtc value.
     *
     * @param lastAcknowledgementSentTimeUtc the lastAcknowledgementSentTimeUtc value to set
     * @return the SecondaryReplicatorStatus object itself.
     */
    public SecondaryReplicatorStatus withLastAcknowledgementSentTimeUtc(DateTime lastAcknowledgementSentTimeUtc) {
        this.lastAcknowledgementSentTimeUtc = lastAcknowledgementSentTimeUtc;
        return this;
    }

}
