/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.cognitiveservices.vision.customvision.training.implementation;

import java.util.List;
import com.microsoft.azure.cognitiveservices.vision.customvision.training.ImageCreateResult;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ImageCreateSummaryInner model.
 */
public class ImageCreateSummaryInner {
    /**
     * The isBatchSuccessful property.
     */
    @JsonProperty(value = "isBatchSuccessful", access = JsonProperty.Access.WRITE_ONLY)
    private boolean isBatchSuccessful;

    /**
     * The images property.
     */
    @JsonProperty(value = "images", access = JsonProperty.Access.WRITE_ONLY)
    private List<ImageCreateResult> images;

    /**
     * Get the isBatchSuccessful value.
     *
     * @return the isBatchSuccessful value
     */
    public boolean isBatchSuccessful() {
        return this.isBatchSuccessful;
    }

    /**
     * Get the images value.
     *
     * @return the images value
     */
    public List<ImageCreateResult> images() {
        return this.images;
    }

}
