/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.servicefabric.implementation;

import com.microsoft.azure.servicefabric.UpgradeKind;
import com.microsoft.azure.servicefabric.RollingUpgradeUpdateDescription;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Describes the parameters for updating an ongoing application upgrade.
 */
public class ApplicationUpgradeUpdateDescriptionInner {
    /**
     * The name of the application, including the 'fabric:' URI scheme.
     */
    @JsonProperty(value = "Name", required = true)
    private String name;

    /**
     * The kind of upgrade out of the following possible values. Possible
     * values include: 'Invalid', 'Rolling'.
     */
    @JsonProperty(value = "UpgradeKind", required = true)
    private UpgradeKind upgradeKind;

    /**
     * Defines a health policy used to evaluate the health of an application or
     * one of its children entities.
     */
    @JsonProperty(value = "ApplicationHealthPolicy")
    private ApplicationHealthPolicyInner applicationHealthPolicy;

    /**
     * Describes the parameters for updating a rolling upgrade of application
     * or cluster.
     */
    @JsonProperty(value = "UpdateDescription")
    private RollingUpgradeUpdateDescription updateDescription;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the ApplicationUpgradeUpdateDescriptionInner object itself.
     */
    public ApplicationUpgradeUpdateDescriptionInner withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the upgradeKind value.
     *
     * @return the upgradeKind value
     */
    public UpgradeKind upgradeKind() {
        return this.upgradeKind;
    }

    /**
     * Set the upgradeKind value.
     *
     * @param upgradeKind the upgradeKind value to set
     * @return the ApplicationUpgradeUpdateDescriptionInner object itself.
     */
    public ApplicationUpgradeUpdateDescriptionInner withUpgradeKind(UpgradeKind upgradeKind) {
        this.upgradeKind = upgradeKind;
        return this;
    }

    /**
     * Get the applicationHealthPolicy value.
     *
     * @return the applicationHealthPolicy value
     */
    public ApplicationHealthPolicyInner applicationHealthPolicy() {
        return this.applicationHealthPolicy;
    }

    /**
     * Set the applicationHealthPolicy value.
     *
     * @param applicationHealthPolicy the applicationHealthPolicy value to set
     * @return the ApplicationUpgradeUpdateDescriptionInner object itself.
     */
    public ApplicationUpgradeUpdateDescriptionInner withApplicationHealthPolicy(ApplicationHealthPolicyInner applicationHealthPolicy) {
        this.applicationHealthPolicy = applicationHealthPolicy;
        return this;
    }

    /**
     * Get the updateDescription value.
     *
     * @return the updateDescription value
     */
    public RollingUpgradeUpdateDescription updateDescription() {
        return this.updateDescription;
    }

    /**
     * Set the updateDescription value.
     *
     * @param updateDescription the updateDescription value to set
     * @return the ApplicationUpgradeUpdateDescriptionInner object itself.
     */
    public ApplicationUpgradeUpdateDescriptionInner withUpdateDescription(RollingUpgradeUpdateDescription updateDescription) {
        this.updateDescription = updateDescription;
        return this;
    }

}
