/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.servicefabric.implementation;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.microsoft.azure.servicefabric.EntityHealth;

/**
 * Information about the health of a Service Fabric node.
 */
public class NodeHealthInner extends EntityHealth {
    /**
     * Name of the node whose health information is described by this object.
     */
    @JsonProperty(value = "Name")
    private String name;

    /**
     * Get the name value.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name value.
     *
     * @param name the name value to set
     * @return the NodeHealthInner object itself.
     */
    public NodeHealthInner withName(String name) {
        this.name = name;
        return this;
    }

}
