/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.servicefabric.implementation;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Describes the parameters for provisioning a cluster.
 */
public class ProvisionFabricDescriptionInner {
    /**
     * The cluster code package file path.
     */
    @JsonProperty(value = "CodeFilePath")
    private String codeFilePath;

    /**
     * The cluster manifest file path.
     */
    @JsonProperty(value = "ClusterManifestFilePath")
    private String clusterManifestFilePath;

    /**
     * Get the codeFilePath value.
     *
     * @return the codeFilePath value
     */
    public String codeFilePath() {
        return this.codeFilePath;
    }

    /**
     * Set the codeFilePath value.
     *
     * @param codeFilePath the codeFilePath value to set
     * @return the ProvisionFabricDescriptionInner object itself.
     */
    public ProvisionFabricDescriptionInner withCodeFilePath(String codeFilePath) {
        this.codeFilePath = codeFilePath;
        return this;
    }

    /**
     * Get the clusterManifestFilePath value.
     *
     * @return the clusterManifestFilePath value
     */
    public String clusterManifestFilePath() {
        return this.clusterManifestFilePath;
    }

    /**
     * Set the clusterManifestFilePath value.
     *
     * @param clusterManifestFilePath the clusterManifestFilePath value to set
     * @return the ProvisionFabricDescriptionInner object itself.
     */
    public ProvisionFabricDescriptionInner withClusterManifestFilePath(String clusterManifestFilePath) {
        this.clusterManifestFilePath = clusterManifestFilePath;
        return this;
    }

}
