/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.azurestack;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Links to product icons.
 */
public class IconUris {
    /**
     * URI to large icon.
     */
    @JsonProperty(value = "large")
    private String large;

    /**
     * URI to wide icon.
     */
    @JsonProperty(value = "wide")
    private String wide;

    /**
     * URI to medium icon.
     */
    @JsonProperty(value = "medium")
    private String medium;

    /**
     * URI to small icon.
     */
    @JsonProperty(value = "small")
    private String small;

    /**
     * URI to hero icon.
     */
    @JsonProperty(value = "hero")
    private String hero;

    /**
     * Get the large value.
     *
     * @return the large value
     */
    public String large() {
        return this.large;
    }

    /**
     * Set the large value.
     *
     * @param large the large value to set
     * @return the IconUris object itself.
     */
    public IconUris withLarge(String large) {
        this.large = large;
        return this;
    }

    /**
     * Get the wide value.
     *
     * @return the wide value
     */
    public String wide() {
        return this.wide;
    }

    /**
     * Set the wide value.
     *
     * @param wide the wide value to set
     * @return the IconUris object itself.
     */
    public IconUris withWide(String wide) {
        this.wide = wide;
        return this;
    }

    /**
     * Get the medium value.
     *
     * @return the medium value
     */
    public String medium() {
        return this.medium;
    }

    /**
     * Set the medium value.
     *
     * @param medium the medium value to set
     * @return the IconUris object itself.
     */
    public IconUris withMedium(String medium) {
        this.medium = medium;
        return this;
    }

    /**
     * Get the small value.
     *
     * @return the small value
     */
    public String small() {
        return this.small;
    }

    /**
     * Set the small value.
     *
     * @param small the small value to set
     * @return the IconUris object itself.
     */
    public IconUris withSmall(String small) {
        this.small = small;
        return this;
    }

    /**
     * Get the hero value.
     *
     * @return the hero value
     */
    public String hero() {
        return this.hero;
    }

    /**
     * Set the hero value.
     *
     * @param hero the hero value to set
     * @return the IconUris object itself.
     */
    public IconUris withHero(String hero) {
        this.hero = hero;
        return this;
    }

}
