/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.servermanagement;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Field description for the implementation of PSHostUserInterface.Prompt.
 */
public class PromptFieldDescription {
    /**
     * The name of the prompt.
     */
    @JsonProperty(value = "name")
    private String name;

    /**
     * The label text of the prompt.
     */
    @JsonProperty(value = "label")
    private String label;

    /**
     * The help message of the prompt.
     */
    @JsonProperty(value = "helpMessage")
    private String helpMessage;

    /**
     * When set to 'true' the prompt field type is a list of values.
     */
    @JsonProperty(value = "promptFieldTypeIsList")
    private Boolean promptFieldTypeIsList;

    /**
     * Possible values include: 'String', 'SecureString', 'Credential'.
     */
    @JsonProperty(value = "promptFieldType")
    private PromptFieldType promptFieldType;

    /**
     * Get the name of the prompt.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Set the name of the prompt.
     *
     * @param name the name value to set
     * @return the PromptFieldDescription object itself.
     */
    public PromptFieldDescription withName(String name) {
        this.name = name;
        return this;
    }

    /**
     * Get the label text of the prompt.
     *
     * @return the label value
     */
    public String label() {
        return this.label;
    }

    /**
     * Set the label text of the prompt.
     *
     * @param label the label value to set
     * @return the PromptFieldDescription object itself.
     */
    public PromptFieldDescription withLabel(String label) {
        this.label = label;
        return this;
    }

    /**
     * Get the help message of the prompt.
     *
     * @return the helpMessage value
     */
    public String helpMessage() {
        return this.helpMessage;
    }

    /**
     * Set the help message of the prompt.
     *
     * @param helpMessage the helpMessage value to set
     * @return the PromptFieldDescription object itself.
     */
    public PromptFieldDescription withHelpMessage(String helpMessage) {
        this.helpMessage = helpMessage;
        return this;
    }

    /**
     * Get when set to 'true' the prompt field type is a list of values.
     *
     * @return the promptFieldTypeIsList value
     */
    public Boolean promptFieldTypeIsList() {
        return this.promptFieldTypeIsList;
    }

    /**
     * Set when set to 'true' the prompt field type is a list of values.
     *
     * @param promptFieldTypeIsList the promptFieldTypeIsList value to set
     * @return the PromptFieldDescription object itself.
     */
    public PromptFieldDescription withPromptFieldTypeIsList(Boolean promptFieldTypeIsList) {
        this.promptFieldTypeIsList = promptFieldTypeIsList;
        return this;
    }

    /**
     * Get possible values include: 'String', 'SecureString', 'Credential'.
     *
     * @return the promptFieldType value
     */
    public PromptFieldType promptFieldType() {
        return this.promptFieldType;
    }

    /**
     * Set possible values include: 'String', 'SecureString', 'Credential'.
     *
     * @param promptFieldType the promptFieldType value to set
     * @return the PromptFieldDescription object itself.
     */
    public PromptFieldDescription withPromptFieldType(PromptFieldType promptFieldType) {
        this.promptFieldType = promptFieldType;
        return this;
    }

}
