/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.servermanagement;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.microsoft.rest.serializer.JsonFlatten;

/**
 * Parameter collection for creation and other operations on sessions.
 */
@JsonFlatten
public class SessionParameters {
    /**
     * Encrypted User name to be used to connect to node.
     */
    @JsonProperty(value = "properties.userName")
    private String userName;

    /**
     * Encrypted Password associated with user name.
     */
    @JsonProperty(value = "properties.password")
    private String password;

    /**
     * Session retention period. Possible values include: 'Session',
     * 'Persistent'.
     */
    @JsonProperty(value = "properties.retentionPeriod")
    private RetentionPeriod retentionPeriod;

    /**
     * Credential data format. Possible values include: 'RsaEncrypted'.
     */
    @JsonProperty(value = "properties.credentialDataFormat")
    private CredentialDataFormat credentialDataFormat;

    /**
     * Encryption certificate thumbprint.
     */
    @JsonProperty(value = "properties.EncryptionCertificateThumbprint")
    private String encryptionCertificateThumbprint;

    /**
     * Get encrypted User name to be used to connect to node.
     *
     * @return the userName value
     */
    public String userName() {
        return this.userName;
    }

    /**
     * Set encrypted User name to be used to connect to node.
     *
     * @param userName the userName value to set
     * @return the SessionParameters object itself.
     */
    public SessionParameters withUserName(String userName) {
        this.userName = userName;
        return this;
    }

    /**
     * Get encrypted Password associated with user name.
     *
     * @return the password value
     */
    public String password() {
        return this.password;
    }

    /**
     * Set encrypted Password associated with user name.
     *
     * @param password the password value to set
     * @return the SessionParameters object itself.
     */
    public SessionParameters withPassword(String password) {
        this.password = password;
        return this;
    }

    /**
     * Get session retention period. Possible values include: 'Session', 'Persistent'.
     *
     * @return the retentionPeriod value
     */
    public RetentionPeriod retentionPeriod() {
        return this.retentionPeriod;
    }

    /**
     * Set session retention period. Possible values include: 'Session', 'Persistent'.
     *
     * @param retentionPeriod the retentionPeriod value to set
     * @return the SessionParameters object itself.
     */
    public SessionParameters withRetentionPeriod(RetentionPeriod retentionPeriod) {
        this.retentionPeriod = retentionPeriod;
        return this;
    }

    /**
     * Get credential data format. Possible values include: 'RsaEncrypted'.
     *
     * @return the credentialDataFormat value
     */
    public CredentialDataFormat credentialDataFormat() {
        return this.credentialDataFormat;
    }

    /**
     * Set credential data format. Possible values include: 'RsaEncrypted'.
     *
     * @param credentialDataFormat the credentialDataFormat value to set
     * @return the SessionParameters object itself.
     */
    public SessionParameters withCredentialDataFormat(CredentialDataFormat credentialDataFormat) {
        this.credentialDataFormat = credentialDataFormat;
        return this;
    }

    /**
     * Get encryption certificate thumbprint.
     *
     * @return the encryptionCertificateThumbprint value
     */
    public String encryptionCertificateThumbprint() {
        return this.encryptionCertificateThumbprint;
    }

    /**
     * Set encryption certificate thumbprint.
     *
     * @param encryptionCertificateThumbprint the encryptionCertificateThumbprint value to set
     * @return the SessionParameters object itself.
     */
    public SessionParameters withEncryptionCertificateThumbprint(String encryptionCertificateThumbprint) {
        this.encryptionCertificateThumbprint = encryptionCertificateThumbprint;
        return this;
    }

}
