/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.compute;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for ReplicationState.
 */
public enum ReplicationState {
    /** Enum value Unknown. */
    UNKNOWN("Unknown"),

    /** Enum value Replicating. */
    REPLICATING("Replicating"),

    /** Enum value Completed. */
    COMPLETED("Completed"),

    /** Enum value Failed. */
    FAILED("Failed");

    /** The actual serialized value for a ReplicationState instance. */
    private String value;

    ReplicationState(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a ReplicationState instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed ReplicationState object, or null if unable to parse.
     */
    @JsonCreator
    public static ReplicationState fromString(String value) {
        ReplicationState[] items = ReplicationState.values();
        for (ReplicationState item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
