/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.datafactory.implementation;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A list of integration runtime resources.
 */
public class IntegrationRuntimeListResponseInner {
    /**
     * List of integration runtimes.
     */
    @JsonProperty(value = "value", required = true)
    private List<IntegrationRuntimeResourceInner> value;

    /**
     * The link to the next page of results, if any remaining results exist.
     */
    @JsonProperty(value = "nextLink")
    private String nextLink;

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public List<IntegrationRuntimeResourceInner> value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the IntegrationRuntimeListResponseInner object itself.
     */
    public IntegrationRuntimeListResponseInner withValue(List<IntegrationRuntimeResourceInner> value) {
        this.value = value;
        return this;
    }

    /**
     * Get the nextLink value.
     *
     * @return the nextLink value
     */
    public String nextLink() {
        return this.nextLink;
    }

    /**
     * Set the nextLink value.
     *
     * @param nextLink the nextLink value to set
     * @return the IntegrationRuntimeListResponseInner object itself.
     */
    public IntegrationRuntimeListResponseInner withNextLink(String nextLink) {
        this.nextLink = nextLink;
        return this;
    }

}
