/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.adhybridhealthservice;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The addtional information for a property.
 */
public class AdditionalInformation {
    /**
     * The title name for the property.
     */
    @JsonProperty(value = "titleName")
    private String titleName;

    /**
     * The title value for the property.
     */
    @JsonProperty(value = "titleValue")
    private String titleValue;

    /**
     * The list of properties which are included in the aditional information.
     */
    @JsonProperty(value = "properties")
    private Object properties;

    /**
     * Get the titleName value.
     *
     * @return the titleName value
     */
    public String titleName() {
        return this.titleName;
    }

    /**
     * Set the titleName value.
     *
     * @param titleName the titleName value to set
     * @return the AdditionalInformation object itself.
     */
    public AdditionalInformation withTitleName(String titleName) {
        this.titleName = titleName;
        return this;
    }

    /**
     * Get the titleValue value.
     *
     * @return the titleValue value
     */
    public String titleValue() {
        return this.titleValue;
    }

    /**
     * Set the titleValue value.
     *
     * @param titleValue the titleValue value to set
     * @return the AdditionalInformation object itself.
     */
    public AdditionalInformation withTitleValue(String titleValue) {
        this.titleValue = titleValue;
        return this;
    }

    /**
     * Get the properties value.
     *
     * @return the properties value
     */
    public Object properties() {
        return this.properties;
    }

    /**
     * Set the properties value.
     *
     * @param properties the properties value to set
     * @return the AdditionalInformation object itself.
     */
    public AdditionalInformation withProperties(Object properties) {
        this.properties = properties;
        return this;
    }

}
