/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.adhybridhealthservice;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The delta in a change that is not re-imported.
 */
public class ChangeNotReimportedDelta {
    /**
     * The anchor.
     */
    @JsonProperty(value = "anchor")
    private String anchor;

    /**
     * The delta attributes for distinguished names.
     */
    @JsonProperty(value = "dnAttributes")
    private List<AttributeDelta> dnAttributes;

    /**
     * The attributes.
     */
    @JsonProperty(value = "attributes")
    private List<AttributeDelta> attributes;

    /**
     * The operation type. Possible values include: 'Undefined', 'None', 'Add',
     * 'Replace', 'Update', 'Delete', 'Obsolete', 'DeletAdd'.
     */
    @JsonProperty(value = "operationType")
    private DeltaOperationType operationType;

    /**
     * Get the anchor value.
     *
     * @return the anchor value
     */
    public String anchor() {
        return this.anchor;
    }

    /**
     * Set the anchor value.
     *
     * @param anchor the anchor value to set
     * @return the ChangeNotReimportedDelta object itself.
     */
    public ChangeNotReimportedDelta withAnchor(String anchor) {
        this.anchor = anchor;
        return this;
    }

    /**
     * Get the dnAttributes value.
     *
     * @return the dnAttributes value
     */
    public List<AttributeDelta> dnAttributes() {
        return this.dnAttributes;
    }

    /**
     * Set the dnAttributes value.
     *
     * @param dnAttributes the dnAttributes value to set
     * @return the ChangeNotReimportedDelta object itself.
     */
    public ChangeNotReimportedDelta withDnAttributes(List<AttributeDelta> dnAttributes) {
        this.dnAttributes = dnAttributes;
        return this;
    }

    /**
     * Get the attributes value.
     *
     * @return the attributes value
     */
    public List<AttributeDelta> attributes() {
        return this.attributes;
    }

    /**
     * Set the attributes value.
     *
     * @param attributes the attributes value to set
     * @return the ChangeNotReimportedDelta object itself.
     */
    public ChangeNotReimportedDelta withAttributes(List<AttributeDelta> attributes) {
        this.attributes = attributes;
        return this;
    }

    /**
     * Get the operationType value.
     *
     * @return the operationType value
     */
    public DeltaOperationType operationType() {
        return this.operationType;
    }

    /**
     * Set the operationType value.
     *
     * @param operationType the operationType value to set
     * @return the ChangeNotReimportedDelta object itself.
     */
    public ChangeNotReimportedDelta withOperationType(DeltaOperationType operationType) {
        this.operationType = operationType;
        return this;
    }

}
