/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.adhybridhealthservice;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The run step for a run profile.
 */
public class RunStep {
    /**
     * The batch size used by the run step.
     */
    @JsonProperty(value = "batchSize")
    private Integer batchSize;

    /**
     * The obect processing limit.
     */
    @JsonProperty(value = "objectProcessLimit")
    private Integer objectProcessLimit;

    /**
     * The object deletion limit.
     */
    @JsonProperty(value = "objectDeleteLimit")
    private Integer objectDeleteLimit;

    /**
     * The page size of the run step.
     */
    @JsonProperty(value = "pageSize")
    private Integer pageSize;

    /**
     * The Id of the partition that a current run setp operation is executing.
     */
    @JsonProperty(value = "partitionId")
    private String partitionId;

    /**
     * The run step operation types. Possible values include: 'Undefined',
     * 'FullImport', 'DeltaImport', 'FullSynchornization',
     * 'DeltaSynchronization', 'ApplyRules', 'Export', 'FullExport',
     * 'FullImportReevaluateRules'.
     */
    @JsonProperty(value = "runStepOperationType")
    private RunStepOperationType runStepOperationType;

    /**
     * Get the batchSize value.
     *
     * @return the batchSize value
     */
    public Integer batchSize() {
        return this.batchSize;
    }

    /**
     * Set the batchSize value.
     *
     * @param batchSize the batchSize value to set
     * @return the RunStep object itself.
     */
    public RunStep withBatchSize(Integer batchSize) {
        this.batchSize = batchSize;
        return this;
    }

    /**
     * Get the objectProcessLimit value.
     *
     * @return the objectProcessLimit value
     */
    public Integer objectProcessLimit() {
        return this.objectProcessLimit;
    }

    /**
     * Set the objectProcessLimit value.
     *
     * @param objectProcessLimit the objectProcessLimit value to set
     * @return the RunStep object itself.
     */
    public RunStep withObjectProcessLimit(Integer objectProcessLimit) {
        this.objectProcessLimit = objectProcessLimit;
        return this;
    }

    /**
     * Get the objectDeleteLimit value.
     *
     * @return the objectDeleteLimit value
     */
    public Integer objectDeleteLimit() {
        return this.objectDeleteLimit;
    }

    /**
     * Set the objectDeleteLimit value.
     *
     * @param objectDeleteLimit the objectDeleteLimit value to set
     * @return the RunStep object itself.
     */
    public RunStep withObjectDeleteLimit(Integer objectDeleteLimit) {
        this.objectDeleteLimit = objectDeleteLimit;
        return this;
    }

    /**
     * Get the pageSize value.
     *
     * @return the pageSize value
     */
    public Integer pageSize() {
        return this.pageSize;
    }

    /**
     * Set the pageSize value.
     *
     * @param pageSize the pageSize value to set
     * @return the RunStep object itself.
     */
    public RunStep withPageSize(Integer pageSize) {
        this.pageSize = pageSize;
        return this;
    }

    /**
     * Get the partitionId value.
     *
     * @return the partitionId value
     */
    public String partitionId() {
        return this.partitionId;
    }

    /**
     * Set the partitionId value.
     *
     * @param partitionId the partitionId value to set
     * @return the RunStep object itself.
     */
    public RunStep withPartitionId(String partitionId) {
        this.partitionId = partitionId;
        return this;
    }

    /**
     * Get the runStepOperationType value.
     *
     * @return the runStepOperationType value
     */
    public RunStepOperationType runStepOperationType() {
        return this.runStepOperationType;
    }

    /**
     * Set the runStepOperationType value.
     *
     * @param runStepOperationType the runStepOperationType value to set
     * @return the RunStep object itself.
     */
    public RunStep withRunStepOperationType(RunStepOperationType runStepOperationType) {
        this.runStepOperationType = runStepOperationType;
        return this;
    }

}
