/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.reservations.implementation;

import java.util.List;
import com.microsoft.azure.management.reservations.SkuProperty;
import com.microsoft.azure.management.reservations.SkuRestriction;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The CatalogInner model.
 */
public class CatalogInner {
    /**
     * The type of resource the SKU applies to.
     */
    @JsonProperty(value = "resourceType", access = JsonProperty.Access.WRITE_ONLY)
    private String resourceType;

    /**
     * The name of SKU.
     */
    @JsonProperty(value = "name", access = JsonProperty.Access.WRITE_ONLY)
    private String name;

    /**
     * Available reservation terms for this resource.
     */
    @JsonProperty(value = "terms", access = JsonProperty.Access.WRITE_ONLY)
    private List<String> terms;

    /**
     * The locations property.
     */
    @JsonProperty(value = "locations", access = JsonProperty.Access.WRITE_ONLY)
    private List<String> locations;

    /**
     * The skuProperties property.
     */
    @JsonProperty(value = "skuProperties", access = JsonProperty.Access.WRITE_ONLY)
    private List<SkuProperty> skuProperties;

    /**
     * The restrictions property.
     */
    @JsonProperty(value = "restrictions", access = JsonProperty.Access.WRITE_ONLY)
    private List<SkuRestriction> restrictions;

    /**
     * Get the type of resource the SKU applies to.
     *
     * @return the resourceType value
     */
    public String resourceType() {
        return this.resourceType;
    }

    /**
     * Get the name of SKU.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Get available reservation terms for this resource.
     *
     * @return the terms value
     */
    public List<String> terms() {
        return this.terms;
    }

    /**
     * Get the locations value.
     *
     * @return the locations value
     */
    public List<String> locations() {
        return this.locations;
    }

    /**
     * Get the skuProperties value.
     *
     * @return the skuProperties value
     */
    public List<SkuProperty> skuProperties() {
        return this.skuProperties;
    }

    /**
     * Get the restrictions value.
     *
     * @return the restrictions value
     */
    public List<SkuRestriction> restrictions() {
        return this.restrictions;
    }

}
