/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.reservations.implementation;

import com.microsoft.azure.management.reservations.SkuName;
import com.microsoft.azure.management.reservations.ReservationProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The ReservationResponseInner model.
 */
public class ReservationResponseInner {
    /**
     * Possible values include: 'westus', 'eastus', 'eastus2',
     * 'northcentralus', 'westus2', 'southcentralus', 'centralus',
     * 'westeurope', 'northeurope', 'eastasia', 'southeastasia', 'japaneast',
     * 'japanwest', 'brazilsouth', 'australiaeast', 'australiasoutheast',
     * 'southindia', 'westindia', 'centralindia', 'canadacentral',
     * 'canadaeast', 'uksouth', 'westcentralus', 'ukwest', 'francecentral',
     * 'francesouth', 'australiac', 'australiac2'.
     */
    @JsonProperty(value = "location")
    private String location;

    /**
     * The etag property.
     */
    @JsonProperty(value = "etag")
    private Integer etag;

    /**
     * Identifier of the reservation.
     */
    @JsonProperty(value = "id", access = JsonProperty.Access.WRITE_ONLY)
    private String id;

    /**
     * Name of the reservation.
     */
    @JsonProperty(value = "name", access = JsonProperty.Access.WRITE_ONLY)
    private String name;

    /**
     * The sku property.
     */
    @JsonProperty(value = "sku")
    private SkuName sku;

    /**
     * The properties property.
     */
    @JsonProperty(value = "properties")
    private ReservationProperties properties;

    /**
     * Type of resource. "Microsoft.Capacity/reservationOrders/reservations".
     */
    @JsonProperty(value = "type", access = JsonProperty.Access.WRITE_ONLY)
    private String type;

    /**
     * Get possible values include: 'westus', 'eastus', 'eastus2', 'northcentralus', 'westus2', 'southcentralus', 'centralus', 'westeurope', 'northeurope', 'eastasia', 'southeastasia', 'japaneast', 'japanwest', 'brazilsouth', 'australiaeast', 'australiasoutheast', 'southindia', 'westindia', 'centralindia', 'canadacentral', 'canadaeast', 'uksouth', 'westcentralus', 'ukwest', 'francecentral', 'francesouth', 'australiac', 'australiac2'.
     *
     * @return the location value
     */
    public String location() {
        return this.location;
    }

    /**
     * Set possible values include: 'westus', 'eastus', 'eastus2', 'northcentralus', 'westus2', 'southcentralus', 'centralus', 'westeurope', 'northeurope', 'eastasia', 'southeastasia', 'japaneast', 'japanwest', 'brazilsouth', 'australiaeast', 'australiasoutheast', 'southindia', 'westindia', 'centralindia', 'canadacentral', 'canadaeast', 'uksouth', 'westcentralus', 'ukwest', 'francecentral', 'francesouth', 'australiac', 'australiac2'.
     *
     * @param location the location value to set
     * @return the ReservationResponseInner object itself.
     */
    public ReservationResponseInner withLocation(String location) {
        this.location = location;
        return this;
    }

    /**
     * Get the etag value.
     *
     * @return the etag value
     */
    public Integer etag() {
        return this.etag;
    }

    /**
     * Set the etag value.
     *
     * @param etag the etag value to set
     * @return the ReservationResponseInner object itself.
     */
    public ReservationResponseInner withEtag(Integer etag) {
        this.etag = etag;
        return this;
    }

    /**
     * Get identifier of the reservation.
     *
     * @return the id value
     */
    public String id() {
        return this.id;
    }

    /**
     * Get name of the reservation.
     *
     * @return the name value
     */
    public String name() {
        return this.name;
    }

    /**
     * Get the sku value.
     *
     * @return the sku value
     */
    public SkuName sku() {
        return this.sku;
    }

    /**
     * Set the sku value.
     *
     * @param sku the sku value to set
     * @return the ReservationResponseInner object itself.
     */
    public ReservationResponseInner withSku(SkuName sku) {
        this.sku = sku;
        return this;
    }

    /**
     * Get the properties value.
     *
     * @return the properties value
     */
    public ReservationProperties properties() {
        return this.properties;
    }

    /**
     * Set the properties value.
     *
     * @param properties the properties value to set
     * @return the ReservationResponseInner object itself.
     */
    public ReservationResponseInner withProperties(ReservationProperties properties) {
        this.properties = properties;
        return this;
    }

    /**
     * Get type of resource. "Microsoft.Capacity/reservationOrders/reservations".
     *
     * @return the type value
     */
    public String type() {
        return this.type;
    }

}
