/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.servicefabric;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Defines an item in ApplicationHealthPolicyMap.
 */
public class ApplicationHealthPolicyMapItem {
    /**
     * The key of the application health policy map item. This is the name of
     * the application.
     */
    @JsonProperty(value = "key", required = true)
    private String key;

    /**
     * The value of the application health policy map item. This is the
     * ApplicationHealthPolicy for this application.
     */
    @JsonProperty(value = "value", required = true)
    private ApplicationHealthPolicy value;

    /**
     * Get the key value.
     *
     * @return the key value
     */
    public String key() {
        return this.key;
    }

    /**
     * Set the key value.
     *
     * @param key the key value to set
     * @return the ApplicationHealthPolicyMapItem object itself.
     */
    public ApplicationHealthPolicyMapItem withKey(String key) {
        this.key = key;
        return this;
    }

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public ApplicationHealthPolicy value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the ApplicationHealthPolicyMapItem object itself.
     */
    public ApplicationHealthPolicyMapItem withValue(ApplicationHealthPolicy value) {
        this.value = value;
        return this;
    }

}
