/**
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 */

package com.microsoft.azure.management.adhybridhealthservice.implementation;

import java.util.List;
import com.microsoft.azure.management.adhybridhealthservice.Connector;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The list of connects for a service.
 */
public class ConnectorsInner {
    /**
     * The value returned by the operation.
     */
    @JsonProperty(value = "value")
    private List<Connector> value;

    /**
     * Get the value value.
     *
     * @return the value value
     */
    public List<Connector> value() {
        return this.value;
    }

    /**
     * Set the value value.
     *
     * @param value the value value to set
     * @return the ConnectorsInner object itself.
     */
    public ConnectorsInner withValue(List<Connector> value) {
        this.value = value;
        return this;
    }

}
